---
# Response message for device status information
float32 cpu_percent
float32 cpu_temp
float32 cpu_freq        # Current CPU frequency in MHz 
float32 cpu_freq_max    # Maximum CPU frequency in MHz
float32 memory_usage
float32 free_disk
float32 latency_mean
float32 latency_p95
float32 fps_mean
int32 error